CREATE TABLE HUMAN (
    ID SERIAL PRIMARY KEY,
    HEIGHT DOUBLE PRECISION CHECK (HEIGHT > 0)
);

CREATE TABLE COORDINATES (
    ID SERIAL PRIMARY KEY,
    X FLOAT CHECK (X > -474),
    Y FLOAT CHECK (Y > -84)
);

CREATE TABLE CITIES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COORDINATES_ID INTEGER NOT NULL REFERENCES COORDINATES(ID),
    CREATION_DATE TIMESTAMP NOT NULL,
    AREA DOUBLE PRECISION NOT NULL CHECK (AREA > 0),
    POPULATION INTEGER NOT NULL CHECK (POPULATION > 0),
    ESTABLISHMENT_DATE TIMESTAMP,
    CAPITAL BOOLEAN,
    METERS_ABOVE_SEA_LEVEL INTEGER,
    TIMEZONE INTEGER CHECK (TIMEZONE > -13 AND TIMEZONE <= 15),
    AGGLOMERATION FLOAT,
    CLIMATE VARCHAR(40),
    GOVERNOR_ID INTEGER REFERENCES HUMAN(ID)
);
